const DO_LOGIN = 'DO_LOGIN';
const LOGOUT = 'LOGOUT';
const GET_WALLETS = 'GET_WALLETS';
const FILE_EXTENSION = 'FILE_EXTENSION';
const EDIT_USER_INFO = 'EDIT_USER_INFO';
const ADD_WALLET = 'ADD_WALLET';
const CHANGE_WALLET_STATUS = 'CHANGE_WALLET_STATUS';
const EDIT_WALLET = 'EDIT_WALLET';
const REGISTER_CUSTOMER = 'REGISTER_CUSTOMER';
const REDIRECT = 'REDIRECT';
const GET_BUDGETS = 'GET_BUDGETS';
const ADD_BUDGET = 'ADD_BUDGET';
const CHANGE_BUDGET_STATUS = 'CHANGE_BUDGET_STATUS';
const EDIT_BUDGET = 'EDIT_BUDGET';
const INITIALIZE = 'INITIALIZE';
const AUTH_ERROR = 'AUTH_ERROR';
const GET_MOVEMENTS = 'GET_MOVEMENTS';
const ADD_MOVEMENT = 'ADD_MOVEMENT';
const EDIT_MOVEMENT = 'EDIT_MOVEMENT';
const GET_INCOMES = 'GET_INCOMES';
const ADD_INCOMES = 'ADD_INCOMES';
const EDIT_INCOMES = 'EDIT_INCOMES';
const EDIT_USER_PASSWORD = 'EDIT_USER_PASSWORD';
const GET_TRANSFERS = 'GET_TRANSFERS';
const ADD_TRANSFERS = 'ADD_INCOMES';
const GET_ALL_REPORTS = 'GET_ALL_REPORTS';
const RESET_REPORTS = 'RESET_REPORTS';
const FORGOT_USER_PASSWORD = 'FORGOT_USER_PASSWORD';
const GET_SERVICES = 'GET_SERVICES';
const DELETE_SHOP = 'DELETE_SHOP';
const ADD_SHOP = 'ADD_SHOP';
const GET_INVOICE = 'GET_INVOICE';
const GET_INVOICES = 'GET_INVOICES';
const SORT_WALLETS_AZ = 'SORT_WALLETS_AZ';
const SORT_WALLETS_ZA = 'SORT_WALLETS_ZA';
const SORT_WALLETS_BALANCE = 'SORT_WALLETS_BALANCE';
const SORT_WALLETS_MIN_BALANCE = 'SORT_WALLETS_MIN_BALANCE';
const GET_INVOICE_ID = 'GET_INVOICE_ID';
const SORT_BUDGETS_AZ = 'SORT_BUDGETS_AZ';
const SORT_BUDGETS_ZA = 'SORT_BUDGETS_ZA';
const SORT_BUDGETS_AMOUNT = 'SORT_BUDGETS_AMOUNT';
const SORT_BUDGETS_MIN_AMOUNT = 'SORT_BUDGETS_MIN_AMOUNT';
const GET_ORDERS = 'GET_ORDERS';
const SORT_ORDERS_STATUS = 'SORT_ORDERS_STATUS';
const SORT_ORDERS_PRIORITY = 'SORT_ORDERS_PRIORITY';
const SORT_ORDERS_PRIORITY_LOW = 'SORT_ORDERS_PRIORITY_LOW';
const SORT_ORDERS_DATE = 'SORT_ORDERS_DATE';
const SORT_ORDERS_DATE_REVERSE = 'SORT_ORDERS_DATE_REVERSE';

export {
  DO_LOGIN,
  GET_WALLETS,
  LOGOUT,
  REGISTER_CUSTOMER,
  REDIRECT,
  ADD_WALLET,
  CHANGE_WALLET_STATUS,
  EDIT_WALLET,
  GET_BUDGETS,
  ADD_BUDGET,
  CHANGE_BUDGET_STATUS,
  EDIT_BUDGET,
  FILE_EXTENSION,
  EDIT_USER_INFO,
  INITIALIZE,
  AUTH_ERROR,
  GET_MOVEMENTS,
  ADD_MOVEMENT,
  EDIT_MOVEMENT,
  GET_INCOMES,
  ADD_INCOMES,
  EDIT_INCOMES,
  EDIT_USER_PASSWORD,
  GET_TRANSFERS,
  ADD_TRANSFERS,
  GET_ALL_REPORTS,
  RESET_REPORTS,
  FORGOT_USER_PASSWORD,
  GET_SERVICES,
  DELETE_SHOP,
  ADD_SHOP,
  GET_INVOICE,
  GET_INVOICES,
  SORT_WALLETS_AZ,
  SORT_WALLETS_ZA,
  SORT_WALLETS_BALANCE,
  SORT_WALLETS_MIN_BALANCE,
  GET_INVOICE_ID,
  SORT_BUDGETS_AZ,
  SORT_BUDGETS_ZA,
  SORT_BUDGETS_AMOUNT,
  SORT_BUDGETS_MIN_AMOUNT,
  GET_ORDERS,
  SORT_ORDERS_STATUS,
  SORT_ORDERS_PRIORITY,
  SORT_ORDERS_PRIORITY_LOW,
  SORT_ORDERS_DATE,
  SORT_ORDERS_DATE_REVERSE,
};
