const DO_LOGIN = 'DO_LOGIN';
const LOGOUT = 'LOGOUT';
const GET_WALLETS = 'GET_WALLETS';
const ADD_WALLET = 'ADD_WALLET';
const CHANGE_WALLET_STATUS = 'CHANGE_WALLET_STATUS';
const EDIT_WALLET = 'EDIT_WALLET';

export { DO_LOGIN, GET_WALLETS, LOGOUT, ADD_WALLET, CHANGE_WALLET_STATUS, EDIT_WALLET };
