const DO_LOGIN = 'DO_LOGIN';
const LOGOUT = 'LOGOUT';
const GET_WALLETS = 'GET_WALLETS';
const FILE_EXTENSION = 'FILE_EXTENSION';
const EDIT_USER_INFO = 'EDIT_USER_INFO';
const ADD_WALLET = 'ADD_WALLET';
const CHANGE_WALLET_STATUS = 'CHANGE_WALLET_STATUS';
const EDIT_WALLET = 'EDIT_WALLET';
const REGISTER_CUSTOMER = 'REGISTER_CUSTOMER';
const REDIRECT = 'REDIRECT';

export { DO_LOGIN, GET_WALLETS, LOGOUT, REGISTER_CUSTOMER, REDIRECT, ADD_WALLET, CHANGE_WALLET_STATUS, EDIT_WALLET,FILE_EXTENSION, EDIT_USER_INFO };