const GET_SERVICES = 'GET_SERVICES';
const EDIT_SERVICES = 'EDIT_SERVICES';
const ADD_SERVICES = 'ADD_SERVICES';
const AUTH_ERROR = 'AUTH_ERROR';
const GET_CATEGORY = 'GET_CATEGORY';
const GET_ORDERS = 'GET_ORDERS';
const EDIT_ORDERS = 'EDIT_ORDERS';
const GET_EMPLOYEES = 'GET_EMPLOYEES';

export {
  GET_SERVICES,
  EDIT_SERVICES,
  ADD_SERVICES,
  AUTH_ERROR,
  GET_CATEGORY,
  GET_ORDERS,
  EDIT_ORDERS,
  GET_EMPLOYEES,
};
