const GET_SERVICES = 'GET_SERVICES';
const EDIT_SERVICES = 'EDIT_SERVICES';
const ADD_SERVICES = 'ADD_SERVICES';
const AUTH_ERROR = 'AUTH_ERROR';
const GET_CATEGORY = 'GET_CATEGORY';
const GET_ORDERS = 'GET_ORDERS';
const EDIT_ORDERS = 'EDIT_ORDERS';
const GET_EMPLOYEES = 'GET_EMPLOYEES';
const SORT_ORDERS_ID = 'SORT_ORDERS_ID';
const SORT_ORDERS_STATUS = 'SORT_ORDERS_STATUS';
const SORT_ORDERS_PRIORITY = 'SORT_ORDERS_PRIORITY';
const SORT_ORDERS_PRIORITY_LOW = 'SORT_ORDERS_PRIORITY_LOW';
const SORT_ORDERS_DATE = 'SORT_ORDERS_DATE';
const SORT_ORDERS_DATE_REVERSE = 'SORT_ORDERS_DATE_REVERSE';

export {
  GET_SERVICES,
  EDIT_SERVICES,
  ADD_SERVICES,
  AUTH_ERROR,
  GET_CATEGORY,
  GET_ORDERS,
  EDIT_ORDERS,
  GET_EMPLOYEES,
  SORT_ORDERS_ID,
  SORT_ORDERS_STATUS,
  SORT_ORDERS_PRIORITY_LOW,
  SORT_ORDERS_PRIORITY,
  SORT_ORDERS_DATE,
  SORT_ORDERS_DATE_REVERSE,
};
