const GET_SERVICES = 'GET_SERVICES';
const EDIT_SERVICES = 'EDIT_SERVICES';
const ADD_SERVICES = 'ADD_SERVICES';
const AUTH_ERROR = 'AUTH_ERROR';
const GET_CATEGORY = 'GET_CATEGORY';

export { GET_SERVICES, EDIT_SERVICES, ADD_SERVICES, AUTH_ERROR, GET_CATEGORY };
